const apikey = "eac6f1f8c57238650553cc7293cee1e2";
const apiURL =
  "https://api.openweathermap.org/data/2.5/weather?&units=metric&q=";
const searchbox = document.querySelector(".search input");
const searchbtn = document.querySelector(".search button");
const suggestionsBox = document.querySelector(".suggestions");
const popularLocations = [
  // 🌍 Countries
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo, Democratic Republic of the",
  "Congo, Republic of the",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czechia",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Ivory Coast",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kosovo",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",

  // 🏙️ Cities
  "Abu Dhabi",
  "Abuja",
  "Accra",
  "Addis Ababa",
  "Adelaide",
  "Ahmedabad",
  "Algiers",
  "Amman",
  "Amsterdam",
  "Ankara",
  "Antalya",
  "Asunción",
  "Athens",
  "Auckland",
  "Baghdad",
  "Baku",
  "Bangkok",
  "Barcelona",
  "Beijing",
  "Beirut",
  "Belgrade",
  "Berlin",
  "Bern",
  "Bogotá",
  "Brasília",
  "Bratislava",
  "Bridgetown",
  "Brussels",
  "Bucharest",
  "Budapest",
  "Buenos Aires",
  "Cairo",
  "Calgary",
  "Canberra",
  "Cancún",
  "Cape Town",
  "Caracas",
  "Casablanca",
  "Chengdu",
  "Chennai",
  "Chicago",
  "Copenhagen",
  "Dakar",
  "Dallas",
  "Damascus",
  "Dar es Salaam",
  "Dhaka",
  "Doha",
  "Dubai",
  "Dublin",
  "Durban",
  "Florence",
  "Frankfurt",
  "Freetown",
  "Geneva",
  "Guadalajara",
  "Guangzhou",
  "Guatemala City",
  "Hanoi",
  "Harare",
  "Havana",
  "Helsinki",
  "Ho Chi Minh City",
  "Hong Kong",
  "Houston",
  "Islamabad",
  "Istanbul",
  "Jakarta",
  "Jeddah",
  "Jerusalem",
  "Johannesburg",
  "Kabul",
  "Kampala",
  "Karachi",
  "Kathmandu",
  "Khartoum",
  "Kyiv",
  "Kingston",
  "Kinshasa",
  "Kuala Lumpur",
  "Kuwait City",
  "Lagos",
  "Lahore",
  "La Paz",
  "Lima",
  "Lisbon",
  "Ljubljana",
  "London",
  "Los Angeles",
  "Luanda",
  "Lusaka",
  "Luxembourg",
  "Macau",
  "Madrid",
  "Manama",
  "Manila",
  "Maputo",
  "Marrakesh",
  "Mecca",
  "Melbourne",
  "Mexico City",
  "Miami",
  "Milan",
  "Minsk",
  "Mogadishu",
  "Monaco",
  "Montevideo",
  "Montreal",
  "Moscow",
  "Mumbai",
  "Munich",
  "Muscat",
  "Nairobi",
  "Nassau",
  "New Delhi",
  "New York",
  "Nicosia",
  "Nouakchott",
  "Osaka",
  "Oslo",
  "Ottawa",
  "Panama City",
  "Paris",
  "Perth",
  "Phnom Penh",
  "Port-au-Prince",
  "Port Louis",
  "Port Moresby",
  "Porto",
  "Prague",
  "Pretoria",
  "Pyongyang",
  "Quito",
  "Rabat",
  "Reykjavik",
  "Riga",
  "Rio de Janeiro",
  "Riyadh",
  "Rome",
  "Saint Petersburg",
  "San Francisco",
  "San José",
  "San Juan",
  "San Salvador",
  "Sana'a",
  "Santiago",
  "Santo Domingo",
  "São Paulo",
  "Sarajevo",
  "Seoul",
  "Shanghai",
  "Singapore",
  "Skopje",
  "Sofia",
  "Stockholm",
  "Suva",
  "Sydney",
  "Taipei",
  "Tallinn",
  "Tashkent",
  "Tbilisi",
  "Tehran",
  "Tel Aviv",
  "Tirana",
  "Tokyo",
  "Toronto",
  "Tripoli",
  "Tunis",
  "Ulaanbaatar",
  "Vaduz",
  "Valletta",
  "Vancouver",
  "Vatican City",
  "Victoria",
  "Vienna",
  "Vientiane",
  "Vilnius",
  "Warsaw",
  "Washington, D.C.",
  "Wellington",
  "Windhoek",
  "Yangon",
  "Yaoundé",
  "Yerevan",
  "Zagreb",
  "Zürich",
];

async function checkWeather(city) {
  const response = await fetch(apiURL + city + `&appid=${apikey}`);

  if (response.status == 404) {
    alert("City not found!");
    return;
  }

  const data = await response.json();
  console.log(data);

  document.querySelector(".city").innerHTML = data.name;
  document.querySelector(".temp").innerHTML = Math.round(data.main.temp) + "°c";
  document.querySelector(".humidity").innerHTML =
    Math.round(data.main.humidity) + "%";
  document.querySelector(".wind").innerHTML =
    Math.round(data.wind.speed) + " km/h";

  if (data.weather[0].main == "Clouds") {
    document.querySelector(".weather-icon").src = "Asset/clouds.png";
  } else if (data.weather[0].main == "Clear") {
    document.querySelector(".weather-icon").src = "Asset/clear.png";
  } else if (data.weather[0].main == "Rain") {
    document.querySelector(".weather-icon").src = "Asset/rain.png";
  } else if (data.weather[0].main == "Drizzle") {
    document.querySelector(".weather-icon").src = "Asset/drizzle.png";
  } else if (data.weather[0].main == "Mist") {
    document.querySelector(".weather-icon").src = "Asset/mist.png";
  }
  document.querySelector(".weather").style.display = "block";
}

searchbtn.addEventListener("click", () => {
  checkWeather(searchbox.value);
});
searchbox.addEventListener("input", () => {
  const input = searchbox.value.toLowerCase();
  suggestionsBox.innerHTML = "";
  suggestionsBox.style.display = "none";

  const filtered = popularLocations.filter((city) =>
    city.toLowerCase().startsWith(input)
  );
  console.log(filtered);
  if (filtered.length > 0) {
    suggestionsBox.style.display = "block";
  }

  filtered.forEach((city) => {
    const suggestionsItem = document.createElement("li");
    suggestionsItem.textContent = city;
    suggestionsItem.addEventListener("click", () => {
      searchbox.value = city;
      suggestionsBox.style.display = "none";
      checkWeather(city);
    });
    suggestionsBox.appendChild(suggestionsItem);
  });
});
